
name: Ubuntu-x86_64

on:
  push:
    paths-ignore:
      - '.github/workflows/alpine-x86_64.yml'
      - '.github/workflows/macos-x86_64.yml'
      - '.github/workflows/macos-arm64.yml'
      - '.github/workflows/ubuntu-aarch64.yml'
      - '.github/workflows/msys-x86_64.yml'
      - '.github/workflows/windows-x86_64.yml'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/cache

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install cmake zlib1g-dev libpcre2-dev clang lcov libcunit1-dev
    - name: Configure CMake
      run: cmake -DCOVERAGE=ON .
    - name: Build
      run: make
    - name: Coverage
      run: make test
    - name: Test
      run: make coverage
